### ISSUE TITLE
How to verify whether SGX enabled in window 11 which is virtual machine enabled SGX in ESX hypervisor of vSphere

### ISSUE THREAD

**Issue by hoyeunglee** [ayeks/SGX-hardware#101]
How to verify whether SGX enabled in window 11 which is virtual machine enabled SGX in ESX hypervisor of vSphere 

What is enclave size of model NUC baby in this case?

Is window 11 in SGX enclave now?

I search common size of enclave is 96MB , does it mean only 96MB memory of virtual machine is protected in SGX enclave ? 
If running office 2021 in window 11 in SGX enabled virtual machine or running Python console in cmd , does these application in enclave ?

**Comment by ayeks** [comment]
Hey, in this repo we collect just SGX capable hardware. Please go to the intel forums for specific questions: https://community.intel.com/t5/Software-Development-Topics/ct-p/software-dev-topics

Thank you!
