### ISSUE TITLE
Report XSAVE data

### ISSUE THREAD

**Issue by marknelsonengineer** [ayeks/SGX-hardware#113]
`XSAVE` configuration data is a little esoteric, especially for users of SGX... BUT if you’re an SGX systems developer, then it’s important to understand the `XSAVE` state of the system.

For example, `XFRM` is set in the following data structures:

  - `SECS.ATTRIBUTES.XFRM`
  - `REPORT.ATTRIBUTES.XFRM`

...and these choices will affect the size of the `XSAVE` area which is part of the `SSAFRAMESIZE` as well as the leftovers from an `AEX`.

So, I'd like to introduce a new feature to explore the system's `XSAVE` capabilities and its current status.

**Comment by ayeks** [comment]
Thanks a lot! Merged.
