### ISSUE TITLE
Dell New XPS 13 Developer Edition works

### ISSUE THREAD

**Issue by FeherMarcell** [ayeks/SGX-hardware#12]
I'm happy to share with you guys that the 2016 [Dell XPS 13 Developer Edition](http://www.dell.com/en-us/shop/productdetails/xps-13-linux) (comes with Ubuntu instead of Windows) supports SGX, however it must be manually enabled in the BIOS.

**Comment by ayeks** [comment]
Thanks! I added it in commit 82547e4.

**Comment by NeatMonster** [comment]
Hello there. Just commenting to add that Dell XPS 15 9560 is also compatible ([source](https://www.reddit.com/r/Dell/comments/5y92qr/intel_sgxv2_supported/deo4zq7/)).

**Comment by ayeks** [comment]
Hey, thanks I added it to the list: d7f33fd
