### ISSUE TITLE
Some SGX enabled hardware

### ISSUE THREAD

**Issue by wireshrink** [ayeks/SGX-hardware#18]
Dell : Inspiron 15 5578 2-in-1 with Intel Kabylake 7500U has Intel SGX support in BIOS.
Intel SGX Platform Capability Tool says

> 
> Intel(R) Software Guard Extensions Platform Capability Tool Version 0.1.1.0
> 
> --------------------------------------------------------------------
> Tue Apr 18 21:55:22 2017
> 
> 
> CPU Brand String: "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz"
> Processor signature: 0x806e9
>         Processor type: 0x0
>         Extended Family: 0x0
>         Family: 0x6
>         Extended Model: 0x8
>         Model: 0xe
>         Stepping: 0x9
> 
> Intel(R) SGX is currently enabled on your platform.
> 
> --------------------------------------------------------------------
> Press any key to continue . . .
> 

I had to enable it in BIOS manually, it was disabled by default.

In addition Dell's support said (I can not confirm that) that Dell Inspiron of models 
5378,5578,7378,7579,7779 should definitely have BIOS SGX support.

I also received the following answer from ASUS support:

> This response is in relation to your recent inquiry about the X456UA notebook's support for Intel® SGX Platform Software. Our technical team has confirmed that it would support the software based on the checks completed.

**Comment by ayeks** [comment]
Hey,
thanks a lot for the info. I added the Dell notebook in commit a76e1ff and the Asus in commit e55612b.
Best regards,
Lars
