### ISSUE TITLE
Surface Pro 4, i5-6300U

### ISSUE THREAD

**Issue by ftes** [ayeks/SGX-hardware#2]
https://software.intel.com/en-us/forums/intel-isa-extensions/topic/606944

I'm in touch with Jeremy, the author of that post, at the moment to find out whether the Surface's BIOS is also SGX-capable.
The [i5-6300U](http://ark.intel.com/products/88190/Intel-Core-i5-6300U-Processor-3M-Cache-up-to-3_00-GHz) seems to be SGX capable despite its not being mentioned in the product change notification with the relevant S-Spec changes.

**Comment by ayeks** [comment]
The Intel product change notification only mentions desktop and server CPUs. The mobile CPUs aren't affected.
However the main problem is that many mainboard vendors are not interested in upgrading their BIOS to support SGX. Only with such an upgrade you are able to set the MSR.IA32_Feature_Control.SGX_Enable Bit.
I will check the Intel thread for more information in the future. Thank you!

**Comment by ayeks** [comment]
I added a label to that issue that a bios update is needed to use SGX. 

Currently there is only a [v1.0 Driver](https://www.microsoft.com/en-us/download/details.aspx?id=49498) from 2/22/2016 available.

**Comment by ayeks** [comment]
Still no driver which enables the SGX settings in the BIOS. Therefore I close the issue.
