### ISSUE TITLE
SuperServer 5019S-MR does not support trusted services

### ISSUE THREAD

**Issue by mitar** [ayeks/SGX-hardware#24]
As described to me by SuperMicro representative:

> it is HW limitation as the X11SSH-F MB is loading with SPS Server Firmware, not ME Firmware

Because of that you do not get `/dev/mei0` service and for Linux it means you do not get trusted services.

I reported it here as well: https://github.com/01org/linux-sgx/issues/114

**Comment by ayeks** [comment]
Thanks for the further information. However, is it still possible to execute SGX with the older firmware 1.0b as you mentioned in issue #6 ?

**Comment by mitar** [comment]
SGX is possible, but trusted services are not. :-(

**Comment by mitar** [comment]
I have not tried to run proper enclave outside of simulation mode yet on the device, so I am not sure if lack of trusted services also means you cannot really even spawn a real enclave.

**Comment by ayeks** [comment]
Okay, without the trusted servers you cannot run the launch enclave which creates the launch keys for your own enclaves. I moved the board to another table in commit 9b141bd.
To my knowledge the only available SGX-capable server today is the [Intel SGX server block](https://www-ssl.intel.com/content/www/us/en/data-center-blocks/business/sgx-server-blocks.html).
Thanks for your information!

**Comment by mitar** [comment]
Yes. :-(

**Comment by jethrogb** [comment]
Are you using the 1.0b BIOS? I'm getting `/dev/mei0` just fine

**Comment by mitar** [comment]
Yes, 1.0b BIOS. But maybe it is ME firmware. Maybe because I upgraded my BIOS first to 2.0 and  then downgraded to 1.0b?

**Comment by mitar** [comment]
@jethrogb Have you found any differences between versions of ME firmware on your machines? Or maybe Linux kernel versions?

**Comment by jethrogb** [comment]
I don't know how to figure out ME version on a running system.

**Comment by jethrogb** [comment]
This configuration has an mei0 device:
```
BIOS Version                              2.0b
Build Date                                07/27/2017
CPLD Version                              02.b1.02

Intel Server Platform Services Configuration

ME BIOS Interface Ver                     1.2
SPS Version                               4.0.3.96
```
This does not:
```
BIOS Version                              2.0b
Build Date                                07/27/2017
CPLD Version                              02.b1.02

Intel Server Platform Services Configuration

ME BIOS Interface Ver                     1.2
SPS Version                               4.1.3.22
```

**Comment by mitar** [comment]
Ooo. So SPS version is the culprit. How to downgrade? :-(

**Comment by ltinerary** [comment]
> This configuration has an mei0 device

 What command should I run to see this output?
Thanks.
