### ISSUE TITLE
Hardware report: MacBook Pro (Retina, 15-inch, Mid 2015)

### ISSUE THREAD

**Issue by pwrdwnsys** [ayeks/SGX-hardware#25]
```
eax: 40661 ebx: 4100800 ecx: 7ffafbff edx: bfebfbff
stepping 1
model 6
family 6
processor type 0
extended model 4
extended family 0
smx: 1

Extended feature bits (EAX=07H, ECX=0H)
eax: 0 ebx: 27ab ecx: 0 edx: 0
sgx available: 0

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)
eax: 7 ebx: 340 ecx: 340 edx: 0
sgx 1 supported: 1
sgx 2 supported: 1
MaxEnclaveSize_Not64: 0
MaxEnclaveSize_64: 0

CPUID Leaf 12H, Sub-Leaf 1 of Intel SGX Capabilities (EAX=12H,ECX=1)
eax: 1 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 2 of Intel SGX Capabilities (EAX=12H,ECX=2)
eax: 100 ebx: 240 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 3 of Intel SGX Capabilities (EAX=12H,ECX=3)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 4 of Intel SGX Capabilities (EAX=12H,ECX=4)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 5 of Intel SGX Capabilities (EAX=12H,ECX=5)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 6 of Intel SGX Capabilities (EAX=12H,ECX=6)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 7 of Intel SGX Capabilities (EAX=12H,ECX=7)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 8 of Intel SGX Capabilities (EAX=12H,ECX=8)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 9 of Intel SGX Capabilities (EAX=12H,ECX=9)
eax: 0 ebx: 0 ecx: 0 edx: 0
```

**Comment by ayeks** [comment]
Hey, that's interesting. Thanks for your contribution!
Are you really able to execute SGX instructions on that machine? There could also be a bug in my testscript because I haven't seen a SGX 2 board from 2015 yet.

**Comment by lacabra** [comment]
I believe the output above of the `test-sgx` is accurate, and the processor on this Mac does not support SGX. According to [the following list](https://everymac.com/systems/by_processor/intel-core-i7-macs.html) this MacBook Pro (Retina, 15-inch, Mid 2015) has an i7-4xxx processor that is not listed in the [ark.intel.com](https://ark.intel.com) database. 

I have a `MacBook Pro "Core i7" 3.1 13" Early 2015`, which has another processor (I7-5557U) not supported either in the Intel database, and the output of the test script shows `sgx available: 0` like the one above.

**Comment by OriWuKids** [comment]
I don't think that's a bug as SGX minimum is required CPU with Secure Key, I also got the rMBP mid-2015 with R9M370X graphics card model, but under ubuntu system, I can only install SDK for compiling but only can run in simulation mode. PSW install definitely fail on this one.
