### ISSUE TITLE
New SGX supported Processors?

### ISSUE THREAD

**Issue by aalanwar** [ayeks/SGX-hardware#27]
Hi 

Thanks for maintaining this very useful repo. What about adding the following processors?. Intel claims that they support SGX and Trusted Execution in these processors. Did anyone report that SGX commands can not be executed on them?

[i7-7920HQ](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7920hq.html)
[i7-7820HK](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7820hk.html)
[i7-7820HQ](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7820hq.html)
[i7-7700T](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7700t.html)
[i7-7700](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7700.html)
[i7-7700K](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7700k.html)
[i7-7660U](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-7660u.html)
[i7-6785R](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-6785r.html)
[i7-6870HQ](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-6870hq.html)
[i5-7600T](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i5-processors/i5-7600t.html)
[i5-7400T](https://www-ssl.intel.com/content/www/us/en/products/processors/core/i5-processors/i5-7400t.html)

Regards

**Comment by ayeks** [comment]
Hey, thanks for your comment. The CPU list is a bit outdated. I will rewrite that section to highlight why the CPUs are listed there. For all other SGX capable CPUs I will use the ark search: [ark.intel.com](https://ark.intel.com/Search/FeatureFilter?productType=processors&SoftwareGuardExtensions=true)
