### ISSUE TITLE
Modify BIOS for Macbook to enable SGX

### ISSUE THREAD

**Issue by imlibra** [ayeks/SGX-hardware#32]
Is it possible to modify the BIOS for Macbook Pro to make it support Intel SGX on Linux?

BIOS update blobs of Mac are encrypted, so SPI programmer is needed to dump a complete binary.

**Comment by ayeks** [comment]
Hi,
I have no Idea how to enable SGX on an Apple Mac. Issue #25 and #26 are going in that same direction. I will leave them open for future discussions.
Best regards
Lars

**Comment by jaouharaa** [comment]
Hello,
am wondering if you still don't have an idea how to enable SGX on mac BIOS, 
attached is the result on running the test and following your explanation i have SGX supported by CPU but not enabled in BIOS, so is there any way to enable it?


<img width="539" alt="Capture d’écran 2020-01-01 à 16 01 36" src="https://user-images.githubusercontent.com/59415070/71642740-3b5c6a80-2cb0-11ea-91c8-3a7f41b1baa3.png">

**Comment by ayeks** [comment]
Hi @jaouharaa ,
Thanks for the report. Unfortunately it is not possible to enable SGX in the BIOS of MacBooks.

Have a look at the following links for official information from Intel and Apple:

* [SGX and the 2016 MacBook Pro ](https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/702781)
* [Intel SGX support? ](https://forums.developer.apple.com/thread/86555)

Best regards
Lars

**Comment by jaouharaa** [comment]
thank you for your answer, and do you have any idea about how to enable it in Windows 10?

**Comment by ayeks** [comment]
@jaouharaa Let me google that for you: https://duckduckgo.com/?q=Getting+Started+with+Intel+Software+Guard+Extensions+SDK+for+Microsoft+Windows

**Comment by jaouharaa** [comment]
@ayeks thank you very much for your help i was able to enable it from bios in windows 10.

**Comment by p-vernaeckt** [comment]
About this issue: now that's it's clear that Apple is ditching Intel, I believe that Apple will never support SGX officially.
 Furthermore: knowing that, is trying to enforce SGX activation through DIY hacks still worth the effort?

**Comment by ayeks** [comment]
@p-vernaeckt I dont know what we could gain from a DIY SGX hack on Intel Macbooks. I rather recommend to look into the [ARM Trustzone](https://en.wikipedia.org/wiki/ARM_architecture#Security_extensions) which maybe can be used on the upcoming Macbooks.

Because the issue got opened on 2017 and it doesnt look like SGX on Macbooks will be possible, I will close this issue. Feel free to reopen if any news come up.
