### ISSUE TITLE
Z370 AORUS Ultra Gaming (rev. 1.0) motherboard has SGX support in BIOS

### ISSUE THREAD

**Issue by wireshrink** [ayeks/SGX-hardware#33]
[motherboard description](https://www.gigabyte.com/Motherboard/Z370-AORUS-Ultra-Gaming-rev-10#kf)
[manual with BIOS decription](http://download.gigabyte.us/FileList/Manual/mb_manual_z370-aorus-ultra-gaming_e.pdf)

I bought a computer with this motherboard, works on Linux too.

**Comment by ayeks** [comment]
Thanks a lot for your contribution!
