### ISSUE TITLE
Potential SGX support for MSI Intel Z370M GAMING PRO AC WiFi

### ISSUE THREAD

**Issue by georgefeakes** [ayeks/SGX-hardware#35]
I'm looking to buy a Mirco-ATX motherboard with SGX support and by the looks of things on the MSI website there is a driver download for Intel Software Guard Extensions listed for this motherboard.

Windows 10 - 64 bit --> Other Drivers:
https://www.msi.com/Motherboard/support/Z370M-GAMING-PRO-AC#down-driver&Win10%2064

This could mean support by I can't say for sure as I don't own it.

**Comment by ayeks** [comment]
Hey thanks for the information. Feel free send an update if you bought the mainboard and tested it for its SGX capability. 

Best regards
Lars

**Comment by ayeks** [comment]
I'll close the issue for now. Feel free to reopen if you have additional information available.
