### ISSUE TITLE
C2059 syntax error 'volatile'

### ISSUE THREAD

**Issue by akefirad** [ayeks/SGX-hardware#4]
Hi, first thanks for the code snippet.
I have VS 2015 Community Ed. installed on Windows 10, but when I try to compile the code (in file test.cpp) it gives the compilation error: `C2059 syntax error 'volatile'`
The command I used is `cl /EHsc test.cpp`
Am I missing something?

**Comment by akefirad** [comment]
For the record I managed to compile the code and run it in Cygwin. Thanks.

**Comment by ayeks** [comment]
Hey,
on Linux it can be compiled with just `gcc ./test-sgx.c`.
I haven't tried it in VS 2015.

If you are on Windows you can have a look into the [Intel SGX SDK](https://software.intel.com/en-us/sgx-sdk). SGX must be enabled in BIOS and therefore works only on the few laptops described in the readme of this repo.
