### ISSUE TITLE
Hardware Report: IBM Cloud

### ISSUE THREAD

**Issue by lacabra** [ayeks/SGX-hardware#43]
[IBM Cloud Data Guard](https://www.ibmdataguard.com/) provides cloud computing infrastructure with support for Intel's SGX. Through IBM Cloud one can contract a single processor bare metal server with SGX support, with the following minimum configuration for $276/month (as of May 2018):

- Processor XEON - E3-1270-v6 Quad Core
- 8 GB RAM
- HD 1TB SATA
- 500 GB public bandwidth
- 100 Mbps Public & Private Network Uplinks
- OS: Ubuntu Linux 16.04 LTS Xenial Xerus (64 bit)

Here's a (partial) report from an instance with the above specifications (will update with full report):

```
eax: 906e9 ebx: 1100800 ecx: 7ffafbff edx: bfebfbff
stepping 9
model 14
family 6
processor type 0
extended model 9
extended family 0
smx: 1

Extended feature bits (EAX=07H, ECX=0H)
eax: 0 ebx: 29c6fbf ecx: 0 edx: 0
sgx available: 1

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)
eax: 1 ebx: 0 ecx: 0 edx: 241f
sgx 1 supported: 1
sgx 2 supported: 0
MaxEnclaveSize_Not64: 1f
MaxEnclaveSize_64: 24
```

SGX capabilities are fully functional and I was able to install [sgx-linux-driver](https://github.com/intel/linux-sgx-driver), and the [sgx-linux](https://github.com/intel/linux-sgx) SDK, and run code inside the enclave. As mentioned in this [README](https://github.com/ayeks/SGX-hardware/#cpus-without-platform-service-enclave-functionality), this processor is part of the Xeon E3 family, which means that the [Trusted Platform Service Functions](https://software.intel.com/en-us/node/709050) (monotonic counters, trusted time) are not available. Otherwise it works as expected.

Issue referenced in #37.

**Comment by ayeks** [comment]
Thanks for the report! So you are able to execute SGX enclaves on the IBM Cloud Data Guard but the following sgx_tservice functions are not available:
```
    sgx_create_pse_session
    sgx_close_pse_session
    sgx_get_ps_sec_prop
    sgx_get_trusted_time
    sgx_create_monotonic_counter_ex
    sgx_create_monotonic_counter
    sgx_destroy_monotonic_counter
    sgx_increment_monotonic_counter
    sgx_read_monotonic_counter
```
[Source](https://software.intel.com/en-us/node/709050)

**Comment by ayeks** [comment]
Thanks a lot for your work! I will close the issue for now. Feel free to reopen it if you want to discuss SGX on IBM with the community.

**Comment by lacabra** [comment]
@ayeks: To your comment above, that is correct: I am able to execute SGX enclaves without the functions that you outline in your comment. And while not ideal, you can circumvent these, so you can arguably have fully capable SGX instances: you should be able to open a TLS connection to an NTP server you trust from within the enclave to obtain a source of trusted time. If you think of trusted monotonic counter as an instance of trusted time, you could get both using the same mechanism (these are suggestions from an Intel SGX architect).

**Comment by ayeks** [comment]
@lacabra Thank you for the clarification! That makes total sense. I will comment that workaround in the documentation.
