### ISSUE TITLE
Alibaba Cloud ECS Bare Metal Instance supports Intel SGX

### ISSUE THREAD

**Issue by Eadom** [ayeks/SGX-hardware#50]
Awesome project! Alibaba Cloud ECS Bare Metal Instance supports Intel SGX:

<https://www.alibabacloud.com/product/ebm?spm=a2c5t.10695662.1996646101.searchclickresult.539275ed2F9WWK>

<https://www.alibabacloud.com/help/doc-detail/60576.html?spm=a2c5t.10695662.1996646101.searchclickresult.539275ed2F9WWK>

It supports SGX1.

**Comment by Eadom** [comment]
I will upload some details soon.

**Comment by OriWuKids** [comment]
It has 2 type of server support with SGX: tech spec as below
Server Name: X-Dragon Cloud Server
1.ecs.ebmg5.24xlarge
Intel Skylake Xeon Platinum 8163 96 vCPU @2.5GHz，384GB RAM，2*10Gbps Bandwidth；
2.ecs.ebmr5.24xlarge
Intel Skylake Xeon Platinum 8163 96 vCPU @2.5GHz，768GB RAM，2*10Gbps Bandwidth；

First 2 devices are available from Sept 29th with the location at Shanghai.

Information reference: 
[Chinese] https://yq.aliyun.com/articles/223458

**Comment by ayeks** [comment]
Thanks for your contributions!

**Comment by lezzokafka** [comment]
> It has 2 type of server support with SGX: tech spec as below
> Server Name: X-Dragon Cloud Server
> 1.ecs.ebmg5.24xlarge
> Intel Skylake Xeon Platinum 8163 96 vCPU @2.5GHz，384GB RAM，2_10Gbps Bandwidth； 2.ecs.ebmr5.24xlarge Intel Skylake Xeon Platinum 8163 96 vCPU @2.5GHz，768GB RAM，2_10Gbps Bandwidth；

Update: Alibaba is now providing some lower-tier instance that supports SGX, for example:
- ebmg5（96-core/384GB);
- ebmc4（32-core/64GB);
- ebmhfg5（8-core/32GB).

Ref:
https://www.alibabacloud.com/product/ebm (under features)
[Chinese] http://www.instancetypes.com/aliyun/ebmhfg5.html
