### ISSUE TITLE
Supermicro X11SSH-F motherboard works

### ISSUE THREAD

**Issue by jkuroda** [ayeks/SGX-hardware#6]
We acquired back in January a [Supermicro 5019-MR](http://www.supermicro.com/products/system/1U/5019/SYS-5019S-MR.cfm) system that uses the [Supermicro X11SSH-F](http://www.supermicro.com/products/motherboard/Xeon/C236_C232/X11SSH-F.cfm) motherboard.

As of BIOS Revision C29 (Dec 29 2015), the system has full support for SGX when used with SGX-enabled E3-1200v5 Skylake Processors.  The same board is in used in two other systems so those systems should also have the same level of support for SGX-enabled processors.

Supermicro advertises that the rest of their [new E3-1200v5 Skylake systems have SGX support](http://www.supermicro.com/newsroom/pressreleases/2015/press150901_Embedded_IoT_Skylake.cfm), but we have not verified this outside of the one system that we have.

**Comment by ayeks** [comment]
Thanks I added it to the list!

**Comment by mitar** [comment]
I just upgrade to 2.0 BIOS and the SGX support is gone. I wrote to Supermicro and they replied:

> This is not an issue.
> From Intel's latest POR, SGX won't be supported with latest 2.0 BIOS on Skylake Server MBs anymore.

Has anyone have a pre 2.0 BIOS I could try to downgrade?

**Comment by mitar** [comment]
Latest firmware with SGX support: [X11SSH6.505.zip](https://github.com/ayeks/SGX-hardware/files/797393/X11SSH6.505.zip)

**Comment by ayeks** [comment]
Oh wow. That is interesting. I added that fact to the list. Thanks a lot for the information. d7f33fd

**Comment by jethrogb** [comment]
BIOS 2.0b restores SGX support and also includes the 7/25 microcode security update.

**Comment by mitar** [comment]
Does it also make system provide `/dev/mei0` consistently?

**Comment by jethrogb** [comment]
Seems unrelated to that, but see my comment in #24
