### ISSUE TITLE
test-sgx should support software enabled SGX

### ISSUE THREAD

**Issue by mitar** [ayeks/SGX-hardware#65]
My NUC came with "software enabled" SGX in BIOS. The `test-sgx` returned that there is no SGX support until I have enabled it manually in BIOS (switched to "enabled"). But I think it would be cool if `test-sgx` could enable SGX "from software" and test it this way. Or at least not somehow that enabling is possible and provide a command line switch to enable it.

**Comment by ayeks** [comment]
Hey mitar! Enabling SGX from this level is unfortunately not possible.  It must be enabled in BIOS.

**Comment by mitar** [comment]
But why does then BIOS have an option saying "software enabled"? So who can then enable it?
