### ISSUE TITLE
Lenovo Ideapad Yoga C940 supports SGX2 

### ISSUE THREAD

**Issue by fangs311** [ayeks/SGX-hardware#77]
The test-sgx return as below, I am running on Windows 10 Home Build 20H2 with latest BIOS version aucn57ww. All the drivers are latest updated. However the Cyberlink Advisor report SGX not supported to play UltraHD BluRay. Does anyone have an advice?

CPU	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
RAM	16.0 GB (15.7 GB 可用)

eax: 706e5 ebx: 6100800 ecx: 7ffafbbf edx: bfebfbff
stepping 5
model 14
family 6
processor type 0
extended model 7
extended family 0
smx: 0

Extended feature bits (EAX=07H, ECX=0H)
eax: 0 ebx: f2bf27ef ecx: 40405f4e edx: bc000410
sgx available: 1
sgx launch control: 1

CPUID Leaf 12H, Sub-Leaf 0 of Intel SGX Capabilities (EAX=12H,ECX=0)
eax: 63 ebx: 1 ecx: 0 edx: 2f1f
sgx 1 supported: 1
sgx 2 supported: 1
MaxEnclaveSize_Not64: 1f
MaxEnclaveSize_64: 2f

CPUID Leaf 12H, Sub-Leaf 1 of Intel SGX Capabilities (EAX=12H,ECX=1)
eax: b6 ebx: 0 ecx: 2e7 edx: 0

CPUID Leaf 12H, Sub-Leaf 2 of Intel SGX Capabilities (EAX=12H,ECX=2)
eax: 50180001 ebx: 0 ecx: bc00001 edx: 0

CPUID Leaf 12H, Sub-Leaf 3 of Intel SGX Capabilities (EAX=12H,ECX=3)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 4 of Intel SGX Capabilities (EAX=12H,ECX=4)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 5 of Intel SGX Capabilities (EAX=12H,ECX=5)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 6 of Intel SGX Capabilities (EAX=12H,ECX=6)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 7 of Intel SGX Capabilities (EAX=12H,ECX=7)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 8 of Intel SGX Capabilities (EAX=12H,ECX=8)
eax: 0 ebx: 0 ecx: 0 edx: 0

CPUID Leaf 12H, Sub-Leaf 9 of Intel SGX Capabilities (EAX=12H,ECX=9)
eax: 0 ebx: 0 ecx: 0 edx: 0

**Comment by ayeks** [comment]
Thanks for your contribution!
