### ISSUE TITLE
Intel advertises SGX support on NUC6i7KYK

### ISSUE THREAD

**Issue by jkuroda** [ayeks/SGX-hardware#9]
https://downloadcenter.intel.com/download/25930/Intel-Software-Guard-Extensions-Software-for-Intel-NUC-Kit-NUC6i7KYK

**Comment by ayeks** [comment]
That applies to the following platforms:

>   Intel® NUC Kit NUC6i3SYK
>   Intel® NUC Kit NUC6i7KYK
>   Intel® NUC Kit NUC6i5SYK
>   Intel® NUC Kit NUC6i3SYH
>   Intel® NUC Kit NUC6i5SYH

I will add this to the overall list.
