### ISSUE TITLE
Is it possible to install vmware vsphere 7.0 to NUC7PJYH for using SGX 2 to use window 7 and office in ESXi ?

### ISSUE THREAD

**Issue by hoyeunglee** [ayeks/SGX-hardware#94]
There is no hard drive in NUC7PJYH kit , is there Amazon link that can buy the hard drive card to install in it?

Is it possible to use apricorn external padlock hard disk with FIPS level 2 hardware encryption to install VMware vsphere 7.0 for using SGX 2 ? 

Will it slow if I install window 7 in vsphere 7.0 ESXi after enable SGX 2?

**Comment by ayeks** [comment]
The NUC7PJYH has a standard SATA port where you can attach any SATA hard drive you want: https://ark.intel.com/content/www/us/en/ark/products/126137/intel-nuc-kit-nuc7pjyh.html Just buy one, attach it, boot from USB stick, install a OS, done. :)

I have no idea on the other two topics. Its probably best to ask this in the official intel developer forum: https://community.intel.com/t5/Intel-Software-Guard-Extensions/bd-p/software-guard-extensions

Best regards
Lars
